services:
  my-server:
    build: . #Dockerfile 을 기준으로 이미지 빌드
    ports:
      - 8080:8080
    depends_on: # depends_on 에 나열한 서비스들이 모두 실행되어야 my-server가 실행된다.
      my-db:
        condition: service_healthy # my-db 가 정상적으로 실행되었는지는 service_healthy 로 판단한다.
  my-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd1234
      MYSQL_DATABASE: mydb # 초기 데이터베이스 생성을 위한 환경변수 추가 (Dockerhub 공식문서 참고)
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck: # service_healthy 판단 기준이 된다.
      test: ["CMD", "mysqladmin", "ping"] # healthcheck 하는 명령어를 작성한다. 이 명령어가 정상적으로 실행된다면 healthy 하다고 판단한다. ( mysql이 정상적으로 실행되고 있는지 ping을 날려봄. )
      interval: 5s # 5초 간격으로 체크
      retries: 10 # 10번까지 재시도
